export interface Tool {
  id: string;
  name: string;
  category: string;
  description: string;
  features: string[];
  link: string;
  pricing: string;
  useCases: string[];
  pros: string[];
  cons: string[];
  alternatives: string[];
  averageRating: number;
  reviewCount: number;
  lastUpdated: string;
}

export const tools: Tool[] = [
  {
    id: "openai-gpt4",
    name: "OpenAI GPT-4",
    category: "General AI Assistants",
    description: "A state-of-the-art language model by OpenAI for advanced content generation, language understanding, and more.",
    features: ["Natural language understanding", "Content generation", "Translation", "Summarization"],
    link: "https://openai.com/gpt-4",
    pricing: "Subscription-based, API available",
    useCases: ["Chatbots", "Content writing", "Education", "Customer support"],
    pros: ["Highly accurate", "Industry leader", "Flexible API"],
    cons: ["API can be expensive at scale", "Occasional hallucinations"],
    alternatives: ["Claude", "Gemini", "Llama 2"],
    averageRating: 4.9,
    reviewCount: 5000,
    lastUpdated: "2026-04-13",
  },
  {
    id: "bard",
    name: "Google Bard",
    category: "General AI Assistants",
    description: "Conversational AI from Google designed to augment productivity and information discovery.",
    features: ["Conversational search", "Integrated with Google products", "Context memory"],
    link: "https://bard.google.com/",
    pricing: "Free",
    useCases: ["Research", "Personal assistant", "Learning"],
    pros: ["Fast", "Good at citations", "Google ecosystem"],
    cons: ["Not available in all countries", "Occasional delays"],
    alternatives: ["ChatGPT", "Claude"],
    averageRating: 4.6,
    reviewCount: 2300,
    lastUpdated: "2026-04-13",
  },
  {
    id: "midjourney",
    name: "Midjourney",
    category: "AI Image Generators",
    description: "An AI tool for creating stunning images and art.",
    features: ["Image Generation", "Style Transfer"],
    link: "https://www.midjourney.com/",
    pricing: "Subscription-based",
    useCases: ["Art Creation", "Design"],
    pros: ["High-quality outputs", "Creative possibilities"],
    cons: ["Costly for professional use"],
    alternatives: ["DALL-E", "Stable Diffusion"],
    averageRating: 4.7,
    reviewCount: 150,
    lastUpdated: "2026-04-13",
  },
  {
    id: "claude",
    name: "Claude",
    category: "General AI Assistants",
    description: "A conversational agent developed by Anthropic.",
    features: ["Natural Language Understanding", "Conversational Abilities"],
    link: "https://www.anthropic.com/claude",
    pricing: "Pay-per-interaction",
    useCases: ["Customer Support", "Virtual Assistants"],
    pros: ["Human-like interactions", "Robust safety features"],
    cons: ["Limited availability"],
    alternatives: ["ChatGPT", "Google Bard"],
    averageRating: 4.6,
    reviewCount: 200,
    lastUpdated: "2026-04-13",
  },
  {
    id: "gemini",
    name: "Gemini",
    category: "General AI Assistants",
    description: "An AI assistant designed to streamline tasks and productivity.",
    features: ["Task Automation", "Scheduling"],
    link: "https://www.gemini.com/",
    pricing: "Freemium",
    useCases: ["Personal Assistance", "Team Collaboration"],
    pros: ["Versatile functionality", "User-friendly interface"],
    cons: ["Limited features in free version"],
    alternatives: ["Microsoft 365 Copilot", "Notion AI"],
    averageRating: 4.4,
    reviewCount: 80,
    lastUpdated: "2026-04-13",
  },
  {
    id: "perplexity",
    name: "Perplexity AI",
    category: "General AI Assistants",
    description: "A powerful tool for obtaining answers to complex questions.",
    features: ["Real-time Q&A", "Source citations"],
    link: "https://www.perplexity.ai/",
    pricing: "Free",
    useCases: ["Research", "Education"],
    pros: ["Accurate answers", "Resource citations"],
    cons: ["Not applicable for all subjects"],
    alternatives: ["Wolfram Alpha", "Google Search"],
    averageRating: 4.5,
    reviewCount: 120,
    lastUpdated: "2026-04-13",
  },
  {
    id: "replit_ghostwriter",
    name: "Replit AI",
    category: "AI Coding Tools",
    description: "An AI-powered code generator for developers.",
    features: ["Code Suggestions", "Debugging Assistance"],
    link: "https://replit.com/ghostwriter",
    pricing: "Subscription-based",
    useCases: ["Software Development", "Learning to Code"],
    pros: ["Enhances productivity", "Easy integration with Replit"],
    cons: ["Limited to Replit platform"],
    alternatives: ["GitHub Copilot", "Tabnine"],
    averageRating: 4.3,
    reviewCount: 90,
    lastUpdated: "2026-04-13",
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    category: "General AI Assistants",
    description: "Conversational AI model by OpenAI.",
    features: ["Chat", "Code Generation", "Analysis"],
    link: "https://chat.openai.com/",
    pricing: "Freemium",
    useCases: ["Writing", "Coding"],
    pros: ["Versatile", "Smart"],
    cons: ["Hallucinates"],
    alternatives: ["Claude"],
    averageRating: 4.8,
    reviewCount: 10000,
    lastUpdated: "2026-04-13",
  },
  {
    id: "microsoft-copilot",
    name: "Microsoft Copilot",
    category: "General AI Assistants",
    description: "AI tool for Microsoft Copilot in the General AI Assistants space.",
    features: ["Microsoft Copilot Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.microsoft-copilot.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in General AI Assistants"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "grok",
    name: "Grok",
    category: "General AI Assistants",
    description: "AI tool for Grok in the General AI Assistants space.",
    features: ["Grok Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.grok.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in General AI Assistants"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "youchat",
    name: "YouChat",
    category: "General AI Assistants",
    description: "AI tool for YouChat in the General AI Assistants space.",
    features: ["YouChat Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.youchat.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in General AI Assistants"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "runway-ml",
    name: "Runway ML",
    category: "AI Video Tools",
    description: "AI tool for Runway ML in the AI Video Tools space.",
    features: ["Runway ML Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.runway-ml.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Video Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "pika-labs",
    name: "Pika Labs",
    category: "AI Video Tools",
    description: "AI tool for Pika Labs in the AI Video Tools space.",
    features: ["Pika Labs Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.pika-labs.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Video Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "synthesia",
    name: "Synthesia",
    category: "AI Video Tools",
    description: "AI tool for Synthesia in the AI Video Tools space.",
    features: ["Synthesia Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.synthesia.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Video Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "heygen",
    name: "HeyGen",
    category: "AI Video Tools",
    description: "AI tool for HeyGen in the AI Video Tools space.",
    features: ["HeyGen Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.heygen.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Video Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "descript",
    name: "Descript",
    category: "AI Video Tools",
    description: "AI tool for Descript in the AI Video Tools space.",
    features: ["Descript Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.descript.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Video Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "sora",
    name: "Sora",
    category: "AI Video Tools",
    description: "AI tool for Sora in the AI Video Tools space.",
    features: ["Sora Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.sora.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Video Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "veedio",
    name: "Veed.io",
    category: "AI Video Tools",
    description: "AI tool for Veed.io in the AI Video Tools space.",
    features: ["Veed.io Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.veedio.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Video Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "capcut-ai",
    name: "CapCut AI",
    category: "AI Video Tools",
    description: "AI tool for CapCut AI in the AI Video Tools space.",
    features: ["CapCut AI Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.capcut.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Video Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "dalle",
    name: "DALL\u00b7E",
    category: "AI Image Generators",
    description: "AI tool for DALL\u00b7E in the AI Image Generators space.",
    features: ["DALL\u00b7E Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.dalle.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Image Generators"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "stable-diffusion",
    name: "Stable Diffusion",
    category: "AI Image Generators",
    description: "AI tool for Stable Diffusion in the AI Image Generators space.",
    features: ["Stable Diffusion Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.stable-diffusion.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Image Generators"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "leonardo-ai",
    name: "Leonardo AI",
    category: "AI Image Generators",
    description: "AI tool for Leonardo AI in the AI Image Generators space.",
    features: ["Leonardo AI Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.leonardo.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Image Generators"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "adobe-firefly",
    name: "Adobe Firefly",
    category: "AI Image Generators",
    description: "AI tool for Adobe Firefly in the AI Image Generators space.",
    features: ["Adobe Firefly Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.adobe-firefly.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Image Generators"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "canva-ai",
    name: "Canva AI",
    category: "AI Image Generators",
    description: "AI tool for Canva AI in the AI Image Generators space.",
    features: ["Canva AI Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.canva.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Image Generators"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "playground-ai",
    name: "Playground AI",
    category: "AI Image Generators",
    description: "AI tool for Playground AI in the AI Image Generators space.",
    features: ["Playground AI Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.playground.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Image Generators"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    category: "AI Voice / Audio Tools",
    description: "AI tool for ElevenLabs in the AI Voice / Audio Tools space.",
    features: ["ElevenLabs Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.elevenlabs.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Voice / Audio Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "murf-ai",
    name: "Murf AI",
    category: "AI Voice / Audio Tools",
    description: "AI tool for Murf AI in the AI Voice / Audio Tools space.",
    features: ["Murf AI Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.murf.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Voice / Audio Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "speechify",
    name: "Speechify",
    category: "AI Voice / Audio Tools",
    description: "AI tool for Speechify in the AI Voice / Audio Tools space.",
    features: ["Speechify Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.speechify.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Voice / Audio Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "resemble-ai",
    name: "Resemble AI",
    category: "AI Voice / Audio Tools",
    description: "AI tool for Resemble AI in the AI Voice / Audio Tools space.",
    features: ["Resemble AI Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.resemble.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Voice / Audio Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "playht",
    name: "PlayHT",
    category: "AI Voice / Audio Tools",
    description: "AI tool for PlayHT in the AI Voice / Audio Tools space.",
    features: ["PlayHT Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.playht.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Voice / Audio Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "voicemod-ai",
    name: "Voicemod AI",
    category: "AI Voice / Audio Tools",
    description: "AI tool for Voicemod AI in the AI Voice / Audio Tools space.",
    features: ["Voicemod AI Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.voicemod.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Voice / Audio Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    category: "AI Coding Tools",
    description: "AI tool for GitHub Copilot in the AI Coding Tools space.",
    features: ["GitHub Copilot Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.github-copilot.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Coding Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "cursor",
    name: "Cursor",
    category: "AI Coding Tools",
    description: "AI tool for Cursor in the AI Coding Tools space.",
    features: ["Cursor Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.cursor.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Coding Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "codeium",
    name: "Codeium",
    category: "AI Coding Tools",
    description: "AI tool for Codeium in the AI Coding Tools space.",
    features: ["Codeium Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.codeium.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Coding Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "tabnine",
    name: "Tabnine",
    category: "AI Coding Tools",
    description: "AI tool for Tabnine in the AI Coding Tools space.",
    features: ["Tabnine Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.tabnine.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Coding Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "amazon-codewhisperer",
    name: "Amazon CodeWhisperer",
    category: "AI Coding Tools",
    description: "AI tool for Amazon CodeWhisperer in the AI Coding Tools space.",
    features: ["Amazon CodeWhisperer Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.amazon-codewhisperer.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Coding Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "elicit",
    name: "Elicit",
    category: "AI Research & Study Tools",
    description: "AI tool for Elicit in the AI Research & Study Tools space.",
    features: ["Elicit Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.elicit.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Research & Study Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "scite",
    name: "Scite",
    category: "AI Research & Study Tools",
    description: "AI tool for Scite in the AI Research & Study Tools space.",
    features: ["Scite Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.scite.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Research & Study Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "consensus",
    name: "Consensus",
    category: "AI Research & Study Tools",
    description: "AI tool for Consensus in the AI Research & Study Tools space.",
    features: ["Consensus Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.consensus.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Research & Study Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "connected-papers",
    name: "Connected Papers",
    category: "AI Research & Study Tools",
    description: "AI tool for Connected Papers in the AI Research & Study Tools space.",
    features: ["Connected Papers Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.connected-papers.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Research & Study Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "notebooklm",
    name: "NotebookLM",
    category: "AI Research & Study Tools",
    description: "AI tool for NotebookLM in the AI Research & Study Tools space.",
    features: ["NotebookLM Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.notebooklm.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Research & Study Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "jasper-ai",
    name: "Jasper AI",
    category: "AI Writing Tools",
    description: "AI tool for Jasper AI in the AI Writing Tools space.",
    features: ["Jasper AI Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.jasper.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Writing Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "copyai",
    name: "Copy.ai",
    category: "AI Writing Tools",
    description: "AI tool for Copy.ai in the AI Writing Tools space.",
    features: ["Copy.ai Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.copyai.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Writing Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "writesonic",
    name: "Writesonic",
    category: "AI Writing Tools",
    description: "AI tool for Writesonic in the AI Writing Tools space.",
    features: ["Writesonic Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.writesonic.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Writing Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "quillbot",
    name: "QuillBot",
    category: "AI Writing Tools",
    description: "AI tool for QuillBot in the AI Writing Tools space.",
    features: ["QuillBot Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.quillbot.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Writing Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "grammarly-ai",
    name: "Grammarly AI",
    category: "AI Writing Tools",
    description: "AI tool for Grammarly AI in the AI Writing Tools space.",
    features: ["Grammarly AI Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.grammarly.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Writing Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    category: "AI Productivity Tools",
    description: "AI tool for Notion AI in the AI Productivity Tools space.",
    features: ["Notion AI Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.notion.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Productivity Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "clickup-ai",
    name: "ClickUp AI",
    category: "AI Productivity Tools",
    description: "AI tool for ClickUp AI in the AI Productivity Tools space.",
    features: ["ClickUp AI Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.clickup.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Productivity Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "motion",
    name: "Motion",
    category: "AI Productivity Tools",
    description: "AI tool for Motion in the AI Productivity Tools space.",
    features: ["Motion Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.motion.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Productivity Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "reclaim-ai",
    name: "Reclaim AI",
    category: "AI Productivity Tools",
    description: "AI tool for Reclaim AI in the AI Productivity Tools space.",
    features: ["Reclaim AI Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.reclaim.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Productivity Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "shortwave",
    name: "Shortwave",
    category: "AI Productivity Tools",
    description: "AI tool for Shortwave in the AI Productivity Tools space.",
    features: ["Shortwave Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.shortwave.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Productivity Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "surfer-seo",
    name: "Surfer SEO",
    category: "AI Marketing & SEO",
    description: "AI tool for Surfer SEO in the AI Marketing & SEO space.",
    features: ["Surfer SEO Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.surfer-seo.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Marketing & SEO"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "clearscope",
    name: "Clearscope",
    category: "AI Marketing & SEO",
    description: "AI tool for Clearscope in the AI Marketing & SEO space.",
    features: ["Clearscope Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.clearscope.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Marketing & SEO"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "frase",
    name: "Frase",
    category: "AI Marketing & SEO",
    description: "AI tool for Frase in the AI Marketing & SEO space.",
    features: ["Frase Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.frase.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Marketing & SEO"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "semrush-ai",
    name: "Semrush AI",
    category: "AI Marketing & SEO",
    description: "AI tool for Semrush AI in the AI Marketing & SEO space.",
    features: ["Semrush AI Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.semrush.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Marketing & SEO"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "figma-ai",
    name: "Figma AI",
    category: "AI For Design / UI / UX",
    description: "AI tool for Figma AI in the AI For Design / UI / UX space.",
    features: ["Figma AI Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.figma.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI For Design / UI / UX"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "uizard",
    name: "Uizard",
    category: "AI For Design / UI / UX",
    description: "AI tool for Uizard in the AI For Design / UI / UX space.",
    features: ["Uizard Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.uizard.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI For Design / UI / UX"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "galileo-ai",
    name: "Galileo AI",
    category: "AI For Design / UI / UX",
    description: "AI tool for Galileo AI in the AI For Design / UI / UX space.",
    features: ["Galileo AI Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.galileo.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI For Design / UI / UX"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "khroma",
    name: "Khroma",
    category: "AI For Design / UI / UX",
    description: "AI tool for Khroma in the AI For Design / UI / UX space.",
    features: ["Khroma Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.khroma.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI For Design / UI / UX"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "zapier-ai",
    name: "Zapier AI",
    category: "AI Automation / Agents",
    description: "AI tool for Zapier AI in the AI Automation / Agents space.",
    features: ["Zapier AI Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.zapier.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Automation / Agents"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "autogpt",
    name: "AutoGPT",
    category: "AI Automation / Agents",
    description: "AI tool for AutoGPT in the AI Automation / Agents space.",
    features: ["AutoGPT Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.autogpt.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Automation / Agents"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "agentgpt",
    name: "AgentGPT",
    category: "AI Automation / Agents",
    description: "AI tool for AgentGPT in the AI Automation / Agents space.",
    features: ["AgentGPT Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.agentgpt.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Automation / Agents"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "langchain",
    name: "LangChain",
    category: "AI Automation / Agents",
    description: "AI tool for LangChain in the AI Automation / Agents space.",
    features: ["LangChain Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.langchain.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Automation / Agents"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "replika",
    name: "Replika",
    category: "AI Mobile / Apps",
    description: "AI tool for Replika in the AI Mobile / Apps space.",
    features: ["Replika Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.replika.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Mobile / Apps"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "character-ai",
    name: "Character AI",
    category: "AI Mobile / Apps",
    description: "AI tool for Character AI in the AI Mobile / Apps space.",
    features: ["Character AI Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.character.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Mobile / Apps"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "lensa-ai",
    name: "Lensa AI",
    category: "AI Mobile / Apps",
    description: "AI tool for Lensa AI in the AI Mobile / Apps space.",
    features: ["Lensa AI Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.lensa.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Mobile / Apps"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "tome-ai",
    name: "Tome AI",
    category: "AI Business Tools",
    description: "AI tool for Tome AI in the AI Business Tools space.",
    features: ["Tome AI Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.tome.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Business Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "durable-ai",
    name: "Durable AI",
    category: "AI Business Tools",
    description: "AI tool for Durable AI in the AI Business Tools space.",
    features: ["Durable AI Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.durable.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Business Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "beautifulai",
    name: "Beautiful.ai",
    category: "AI Business Tools",
    description: "AI tool for Beautiful.ai in the AI Business Tools space.",
    features: ["Beautiful.ai Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.beautifulai.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Business Tools"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "datarobot",
    name: "DataRobot",
    category: "AI Data / Analytics",
    description: "AI tool for DataRobot in the AI Data / Analytics space.",
    features: ["DataRobot Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.datarobot.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Data / Analytics"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "h2oai",
    name: "H2O.ai",
    category: "AI Data / Analytics",
    description: "AI tool for H2O.ai in the AI Data / Analytics space.",
    features: ["H2O.ai Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.h2oai.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Data / Analytics"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
  {
    id: "rapidminer",
    name: "RapidMiner",
    category: "AI Data / Analytics",
    description: "AI tool for RapidMiner in the AI Data / Analytics space.",
    features: ["RapidMiner Feature 1", "AI Capabilities", "Automation"],
    link: "https://www.rapidminer.com",
    pricing: "Freemium / Premium",
    useCases: ["Professional use", "Personal use", "Enterprise workflows"],
    pros: ["Innovative", "Time-saving"],
    cons: ["Requires learning curve", "May require subscription"],
    alternatives: ["Other tools in AI Data / Analytics"],
    averageRating: 4.5,
    reviewCount: 100,
    lastUpdated: "2026-04-13",
  },
];

export const categories = [
  "General AI Assistants",
  "AI Video Tools",
  "AI Image Generators",
  "AI Voice / Audio Tools",
  "AI Coding Tools",
  "AI Research & Study Tools",
  "AI Writing Tools",
  "AI Productivity Tools",
  "AI Marketing & SEO",
  "AI For Design / UI / UX",
  "AI Automation / Agents",
  "AI Mobile / Apps",
  "AI Business Tools",
  "AI Data / Analytics",
  "Natural Language Processing",
  "Chatbots",
  "Creative AI",
  "Business AI",
  "NLP Frameworks",
  "Machine Learning",
  "Cloud AI",
  "Analytics",
];
